use_frameworks!

platform :ios, '8.0'

target 'CYKPodLib_Example' do
  pod 'CYKPodLib', :path => '../'

  target 'CYKPodLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
